spring.application.name=magi

# spring.datasource.url=jdbc:mysql://localhost:3306/agimuseum?zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database=mysql

spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect

spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:13343/railway?zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=eHYaNuNwqJNjUAYNhSVUMcaLkUaJdjYf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
